services:
  db:
    image: postgres:16
    container_name: bookstore_db
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore
    ports:
      - "54329:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: